---
- name: ensure apache is at the latest version
  packages:
    name: python3
    state: latest
# python-pip
# python -m pip install --upgrade pip # install pip package manager
# pip install --upgrade autopep8

- name: Install requirements on Debian based distros
  shell: |
    python -mpip install --user --pre -U "{{ item }}"
  loop:
    - flake8
    - pipenv
