- hosts: local
  become: yes
  become_user: mohammadne
  # pre_tasks:
  #   - include_tasks: tasks/clone.yaml
  roles:
    # - { role: development/alacritty }
    # - { role: development/core }
    - { role: development/tmux }
    # - { role: development/zsh }
