- hosts: local
  # become: yes
  # pre_tasks:
  #   - include_tasks: tasks/clone.yaml
  vars_files: vars/main.yaml
  tasks:
  - import_tasks: tasks/main.yaml

- hosts: servers
  # become: yes
  # pre_tasks:
  #   - include_tasks: tasks/clone.yaml
  vars_files: vars/main.yaml
  tasks:
  - import_tasks: tasks/main.yaml
