---
- name: setup environment
  shell: |
    go env -w GOPROXY="https://goproxy.io,goproxy.cn,direct"
    go env -w GONOSUMDB="git.cafebazaar.ir"
    go env -w GOPRIVATE="git.cafebazaar.ir"
    go env # print environment

# useful packages
# require_go github.com/golangci/golangci-lint/cmd/golangci-lint
# require_go mvdan.cc/gofumpt
# require_go golang.org/x/tools/cmd/goimports
# require_go golang.org/x/tools/gopls
# require_go golang.org/dl/gotip
# require_go github.com/go-delve/delve/cmd/dlv
# age
