---
- name: Check if the repository is already exists
  stat:
    path: "{{ repository_path }}/dotfiles"
  register: clone_check

- name: Clone the repository if the path doesn't exist
  git:
    repo: "https://github.com/{{ repository_url }}.git"
    dest: "{{ repository_path }}"
  when: not clone_check.stat.exists

- name: Switch to the git directory after clone
  shell: git remote set-url origin git@github.com:{{ repository_url }}.git
  when: not clone_check.stat.exists
