- name: TODO
  package:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - vim

- name: todo
  shell: |
    ln -s "$SOURCE/files/vim/vimrc" "$HOME/.vimrc"

- name: todo
  shell: |
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    vim +PlugInstall +qa || echo "Something went wrong installing vim plugins."
