# prevent from duplicate records in path
typeset -U path

# set PATH so it includes user's local private bin if it exists
if [ -d "$HOME/.local/bin" ]; then
	path+=("$HOME/.local/bin")
fi

# add golang related environments if go binary has been installed
_go_binary="/usr/local/go/bin/go" # go binary address
if command -v $_go_binary &> /dev/null; then
  export GOROOT=$($_go_binary env GOROOT)
  export GOPATH=$($_go_binary env GOPATH)
  PATH=$PATH:$GOROOT/bin:$GOPATH
fi

# add cargo if cargo has been installed
if command -v cargo &> /dev/null; then
  export CARGOPATH=~/.cargo/bin
  PATH=$PATH:$CARGOPATH
fi

# replace cat with bat for viewing manpages
if command -v bat &>/dev/null; then
	export MANPAGER="sh -c 'col -bx | bat -l man -p'"
fi

# languages
export LANG="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

EDITOR="$(which vim)"
export EDITOR

DISABLE_AUTO_TITLE='true'
export DISABLE_AUTO_TITLE

TERM="xterm-256color"
export TERM

# should be the last line
export PATH
