---
- name: Install requirements on Debian based distros
  package:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - htop # process viewer
    - dua-cli # Disk Usage Analyzer
    - cpupower # processor power managment
    - reflector # retrieve the latest mirror list from the Arch
    - usbutils # USB utilities
