---
- name: Install network requirements on Debian based distros
  package:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - curl # network data transfer utility
    - mtr 
    - inetutils
    - websocat
    - fuse2
    - aria2 # download manager
    - bandwhich # bandwidth utilization tool
    - speedtest-cli # speedtest cli
    - openbsd-netcat
    - telnet
    - tcpdump
    - ss
    - tshark
    - wireshark

- name: Install requirements on Debian based distros
  package:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - htop # process viewer
    - dua-cli # Disk Usage Analyzer
    - cpupower # processor power managment
    - reflector # retrieve the latest mirror list from the Arch
    - usbutils # USB utilities
