- name: Install requirements on Debian based distros
  package:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - git

- name: Install requirements on Debian based distros
  when: ansible_os_family == 'Debian'
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - build-essential

- name: Install requirements on RedHat based distros
  when: ansible_os_family == 'RedHat'
  dnf:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - "@Development tools"
