---
# - name: install dependencies
#   package:
#     name: "{{ item }}"
#     state: latest
#     update_cache: yes
#   loop:
#     - tmux
#     - tmuxp

- name: Symlink tmux
  include_tasks: tasks/linker.yaml
  vars:
    role: "{{ role_name }}"
    name: "Tmux"
    source: "files/tmux"
    destination: "{{ ansible_env.HOME }}/.config/tmux"

- name: install tmux plugins
  shell: |
    tpm_path="$HOME/.local/share/tmux/plugins/tpm"
    if [ ! -d "$tpm_path" ]; then
      git clone https://github.com/tmux-plugins/tpm "$tpm_path"
    fi
    "$tpm_path/bin/install_plugins"

# linker "tmuxp" "$configs_dir/tmux" "$HOME/.config/tmuxp"
# linker "tmuxs" "$configs_dir/tmux" "$HOME/.config/tmuxs"
