# color references: https://unpkg.com/browse/alacritty-themes

colors:
  # Default colors
  primary:
    background: "0x1e2127"
    foreground: "0xabb2bf"

  # Normal colors
  normal:
    black: "0x1e2127"
    red: "0xe06c75"
    green: "0x98c379"
    yellow: "0xd19a66"
    blue: "0x61afef"
    magenta: "0xc678dd"
    cyan: "0x56b6c2"
    white: "0xabb2bf"

  # Bright colors
  bright:
    black: "0x5c6370"
    red: "0xe06c75"
    green: "0x98c379"
    yellow: "0xd19a66"
    blue: "0x61afef"
    magenta: "0xc678dd"
    cyan: "0x56b6c2"
    white: "0xffffff"

font:
  size: 14
  normal:
    family: FiraCode Nerd Font
    style: Regular
  bold:
    family: FiraCode Nerd Font
    style: Bold
  italic:
    family: FiraCode Nerd Font
    style: Italic

live_config_reload: true

window:
  opacity: 0.95

cursor:
  style: Beam
  # If this is `true`, the cursor will be rendered as a hollow box when the window is not focused.
  unfocused_hollow: true

mouse:
  # If this is `true`, the cursor is temporarily hidden when typing.
  hide_when_typing: true
  # url:
  #   launcher:
  #     program: open
  #   modifiers: Command

key_bindings:
  - { key: Key0, mods: Control, action: ResetFontSize }
  - { key: Equals, mods: Control, action: IncreaseFontSize }
  - { key: Plus, mods: Control, action: IncreaseFontSize }
  - { key: NumpadAdd, mods: Control, action: IncreaseFontSize }
  - { key: Minus, mods: Control, action: DecreaseFontSize }
  - { key: NumpadSubtract, mods: Control, action: DecreaseFontSize }

shell:
  program: /bin/zsh
