---
- name: Perform variable assertion
  ansible.builtin.assert:
    that:
      - name is defined
      - source is defined
      - destination is defined
    fail_msg: "One or more variables are not defined, but they should be."
  ignore_errors: false

- name: Create fullpath from relative source path
  ansible.builtin.set_fact:
    source: "{{ repository_path }}/roles/{{ source }}"

- name: "Create parent directory for {{ name }} if it's missing"
  ansible.builtin.shell: |
    parent_directory="$(dirname "$destination")"
    mkdir -p $parent_directory

- name: Gather information about the source path
  stat:
    path: "{{ source }}"
  register: source_info

- name: Gather information about the destination path
  stat:
    path: "{{ destination }}"
  register: destination_info

- name: Check if source is a symlink to the destination
  set_fact:
    is_symlink: "{{ source_info.stat.islnk is defined and source_info.stat.islnk and source_info.stat.lnk_target == destination_info.stat.path }}"

- name: Perform another task based on symlink status
  debug:
    msg: "destination path is already a symlink to the source path."
  when: is_symlink

# - name: "Create symbolic link for {{ name }} config"
#   file:
#     src: "{{ source }}"
#     dest: "{{ destination }}"
#     state: link
#   when: not is_symlink
