---
# - name: Add Alacritty repository from PPA and install its signing key
#   ansible.builtin.apt_repository:
#     repo: ppa:aslatter/ppa
#   when: ansible_os_family == 'Debian'

# - name: Install the latest version of Alacritty
#   ansible.builtin.package:
#     name:
#       - alacritty
#     state: latest

- name: Symlink Alacritty
  include_tasks: tasks/linker.yaml
  vars:
    role: "{{ role_name }}"
    name: "Alacritty"
    source: "files/config.yml"
    destination: "{{ ansible_env.HOME }}/.config/alacritty.yml"
