# nord color references: https://github.com/arcticicestudio/nord-alacritty

font:
  size: 12
  normal:
    family: FiraCode Nerd Font
    style: Regular
  bold:
    family: FiraCode Nerd Font
    style: SemiBold
  italic:
    family: FiraCode Nerd Font
    style: ExtraLight Italic
  builtin_box_drawing: true
  offset:
    x: 0
    y: 5

live_config_reload: true

window:
  opacity: 0.9
  padding:
    x: 10
    y: 10

cursor:
  style: Beam
  # If this is `true`, the cursor will be rendered as a hollow box when the window is not focused.
  unfocused_hollow: true

mouse:
  # If this is `true`, the cursor is temporarily hidden when typing.
  hide_when_typing: true

key_bindings:
  - { key: Key0, mods: Control, action: ResetFontSize }
  - { key: Equals, mods: Control, action: IncreaseFontSize }
  - { key: Plus, mods: Control, action: IncreaseFontSize }
  - { key: NumpadAdd, mods: Control, action: IncreaseFontSize }
  - { key: Minus, mods: Control, action: DecreaseFontSize }
  - { key: NumpadSubtract, mods: Control, action: DecreaseFontSize }

shell:
  program: /bin/fish
