# color references: https://unpkg.com/browse/alacritty-themes

colors:
  # Default colors
  primary:
    background: "#2E3440"
    foreground: "#D8DEE9"

  # Normal colors
  normal:
    black: "#3B4252"
    red: "#BF616A"
    green: "#A3BE8C"
    yellow: "#EBCB8B"
    blue: "#81A1C1"
    magenta: "#B48EAD"
    cyan: "#88C0D0"
    white: "#E5E9F0"

  # Bright colors
  bright:
    black: "#4C566A"
    red: "#BF616A"
    green: "#A3BE8C"
    yellow: "#EBCB8B"
    blue: "#81A1C1"
    magenta: "#B48EAD"
    cyan: "#8FBCBB"
    white: "#ECEFF4"

font:
  size: 14
  normal:
    family: FiraCode Nerd Font
    style: Regular
  bold:
    family: FiraCode Nerd Font
    style: SemiBold
  italic:
    family: FiraCode Nerd Font
    style: ExtraLight Italic
  builtin_box_drawing: true

live_config_reload: true

window:
  opacity: 0.95
  padding:
    y: 5

cursor:
  style: Beam
  # If this is `true`, the cursor will be rendered as a hollow box when the window is not focused.
  unfocused_hollow: true

mouse:
  # If this is `true`, the cursor is temporarily hidden when typing.
  hide_when_typing: true

key_bindings:
  - { key: Key0, mods: Control, action: ResetFontSize }
  - { key: Equals, mods: Control, action: IncreaseFontSize }
  - { key: Plus, mods: Control, action: IncreaseFontSize }
  - { key: NumpadAdd, mods: Control, action: IncreaseFontSize }
  - { key: Minus, mods: Control, action: DecreaseFontSize }
  - { key: NumpadSubtract, mods: Control, action: DecreaseFontSize }

shell:
  program: /bin/zsh
