---
name: install
on:
  push:
    paths:
      - .github/workflows/install.yaml
      - scripts/src/base.sh
      - scripts/install.sh

jobs:
  base:
    runs-on: ubuntu-22.04
    name: Build on ubuntu-22.04 armv7
    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: armv7
          distro: ubuntu22.04
          githubToken: ${{ github.token }}
          run: |
            echo "hi"
      - name: Get the output
        run: |
          echo "The validate output was: ${{ env.validate }}"
          echo "The dependencies output was: ${{ env.dependencies }}"
