---
name: install
on:
  push:
    paths:
      - .github/workflows/install.yaml
      - scripts/src/base.sh
      - scripts/install.sh

jobs:
  armv7_job:
    # The host should always be Linux
    runs-on: ubuntu-22.04
    name: Build on ubuntu-22.04 armv7
    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: armv7
          distro: ubuntu22.04
          githubToken: ${{ github.token }}
          run: |
            echo ::set-output name=validate::$(test "$(readlink -f ~/.config/git)" = "$(pwd)/configs/git")
            echo ::set-output name=dependencies::$(bash -c hash nvim batcat bmon)

      - name: Get the output
        run: |
          echo "The validate output was ${{ steps.runcmd.outputs.validate }}"
          echo "The dependencies output was ${{ steps.runcmd.outputs.dependencies }}"
